democrateam/consul

config/deploy/production.rb
Add the ability to deploy any specific branch when deploying to production using capistrano
=> Ability to deploy specific branch in production with capistrano

config/initializers/errbit.rb
Do not send the 404 errors to Errbit
=> Errbit + Airbrake: Ignore 404 errors

config/deploy/staging.rb
Use the same roles in staging than in production
=> Improve deployments with capistrano

config/environments/staging.rb
Not have DEBUG level for logs in staging environments
=> Set log level to INFO for staging environments

.travis.yml
=> Update Ruby version for travis

config/deploy.rb
Always execute the update release tasks when deploying
=> Always execute release tasks when deploying

config/initializers/errbit.rb
Ignore more not real errors in errbit
=> Ignore more not real errors in errbit

config/locales/en/general.yml, config/locales/es/general.yml, config/locales/es/legislation.yml, spec/system/custom/welcome_page_spec.rb
Add missing Spanish translations.
=> Add missing Spanish translations

app/assets/stylesheets/base.scss, app/components/admin/budgets/index_component.html.erb, app/components/budgets/ballot/investment_component.html.erb, app/components/budgets/budget_component.html.erb, app/components/budgets/groups_and_headings_component.html.erb, app/components/widget/feeds/budget_component.html.erb, app/components/widget/feeds/budget_component.rb, app/helpers/budgets_helper.rb, app/views/admin/budgets/_form.html.erb, app/views/budgets/investments/_votes.html.erb, app/views/budgets/results/show.html.erb, app/views/debates/_debate.html.erb, config/locales/custom/nl/admin.yml, config/locales/custom/nl/budgets.yml, config/locales/custom/nl/general.yml, spec/system/budgets/ballots_spec.rb, spec/system/budgets/budgets_spec.rb, spec/system/budgets/votes_spec.rb
This is a backport of https://github.com/StemvanGroningen/consul/pull/127/.
- Add custom translations.
- Update base styles.
- Remove duplicated title.
- Remove duplicated icon.
- Fix image on feeds budget.
- Remove budget description on budget page.
- Do not show confirm message if user can vote in all headings.
- Do not use wysiwyg on index debate description.
- Add missing css class.
- Show heading links on finished budgets.
- Update results table size.
- Update html on admin budgets form.
=> Backport: content for the new release

config/locales/custom/nl/activerecord.yml, config/locales/custom/nl/sdg.yml, config/locales/custom/nl/sdg_management.yml
This is a backport of https://github.com/StemvanGroningen/consul/pull/128.
Add custom `nl` translations for SDG content.
=> SDG Dutch translations

Gemfile
This is a backport of the PR https://github.com/sisli-consul/consul/pull/17
=> Backport from Sisli

app/models/budget/ballot.rb, app/models/site_customization/image.rb, app/views/budgets/_investment.html.erb, app/views/budgets/executions/_image.html.erb, config/locales/custom/nl/general.yml, spec/system/admin/site_customization/images_spec.rb
This is a backport of the PRs:
- https://github.com/StemvanGroningen/consul/pull/120
- https://github.com/StemvanGroningen/consul/pull/121
- https://github.com/StemvanGroningen/consul/pull/129
=> Backports from Groningen

app/views/custom/polls/_poll_group.html.erb, spec/system/polls/polls_spec.rb
This is a backport of https://github.com/sisli-consul/consul/pull/24.
Calculate correctly remaining days to participate on polls.
=> Calculate correctly remaining days to participate on polls

app/assets/stylesheets/base.scss
Fix word break on budget investments index list.
=> Fix word break on budget investments index list

app/assets/stylesheets/base.scss
- Prevent grow font size for all elements.
- Fix headers with full background images.
=> Enhacement

lib/tasks/budgets.rake
Backport of https://github.com/StemvanGroningen/consul/pull/138/commits/29c050309c3dbc51699e746ef837829d5c76a7f1
Fix rake to update custom budget links
=> Fix rake to update custom budget links

spec/shared/system/nested_imageable.rb
Remove duplicated method `imageable_fill_new_valid_budget` on nested imageable.
=> Remove duplicated method on nested imageable

app/components/shared/comments_component.html.erb, app/views/comments/_comment_tree.html.erb, spec/system/comments/budget_investments_spec.rb, spec/system/comments/debates_spec.rb, spec/system/comments/legislation_questions_spec.rb, spec/system/comments/polls_spec.rb, spec/system/comments/proposals_spec.rb, spec/system/comments/topics_spec.rb
Show comments order only if there are comments.
=> Show comments order only if there are comments

app/assets/stylesheets/_consul_settings.scss, app/assets/stylesheets/base.scss, app/components/admin/budgets/form_component.html.erb, app/components/budgets/investment_component.html.erb, app/components/budgets/investment_component.rb, app/components/budgets/supports_info_component.html.erb, app/models/image.rb, app/views/budgets/investments/edit.html.erb, app/views/dashboard/polls/_question_answer_fields.html.erb, app/views/legislation/proposals/_form.html.erb, app/views/legislation/proposals/new.html.erb, app/views/proposals/summary.html.erb, config/locales/nl/activerecord.yml, config/locales/nl/admin.yml, config/locales/nl/budgets.yml, spec/components/budgets/supports_info_component_spec.rb, spec/system/budgets/budgets_spec.rb
Selected backport from https://github.com/StemvanGroningen/consul/pull/138/commits/6854ffc72e8899a17c1ab12c5c3b1de8da015de0.
Fixes after update to 1.4.1.
=> Fixes after update to 1.4.1

app/components/widget/feeds/feed_component.html.erb, app/components/widget/feeds/process_component.html.erb, app/components/widget/feeds/process_component.rb, app/models/site_customization/image.rb, spec/system/admin/site_customization/images_spec.rb
Add welcome process image to admin site customization.
=> Add welcome process image to admin site customization

app/views/budgets/ballot/_progress_bar.html.erb, app/views/budgets/investments/_header.html.erb, spec/system/budgets/investments_spec.rb
Do not show progress bar with hidden money.
=> Do not show progress bar with hidden money

app/components/admin/budget_headings/headings_component.html.erb, app/controllers/admin/budgets_wizard/budgets_controller.rb, app/views/valuation/budget_investments/_dossier_form.html.erb, spec/system/admin/budgets_spec.rb, spec/system/admin/budgets_wizard/budgets_spec.rb
Add missing hide money content and specs.
=> Add missing hide money content and specs

app/components/budgets/budget_component.html.erb, spec/system/budgets/budgets_spec.rb
Show budgets map only if feature is enabled.
=> Show budgets map only if feature is enabled

config/locales/es/admin.yml
Remove duplicated translation.
=> Remove duplicated translation

app/assets/stylesheets/base.scss
Remove unnecessary CSS to show border-bottom on the top bar menu.
=> Remove unnecessary CSS

config/locales/custom/nl/admin.yml
Fix translation on `admin.yml`.
=> Fix translation

app/assets/stylesheets/base.scss, app/components/admin/widget/cards/row_component.html.erb, app/views/admin/widget/cards/_form.html.erb, app/views/shared/_header_content.html.erb, spec/system/admin/homepage/homepage_spec.rb, spec/system/admin/widgets/cards_spec.rb, spec/system/custom/admin/cards_spec.rb
Add wysiwyg to header card description.
=> Add wysiwyg to header card description

app/assets/stylesheets/base.scss
Fix styles for headers with background images.
=> Fix styles for headers with background images

app/assets/stylesheets/base.scss
=> Fix lint warnings

app/models/budget/heading.rb, spec/system/admin/site_customization/content_blocks_spec.rb
Remove budget content block when delete a heading.
=> Remove budget content block when delete a heading

app/assets/stylesheets/base.scss
- Improve styles for admin header.
=> Admin styles

app/assets/stylesheets/base.scss
=> Fix verification form layout

config/locales/custom/nl/budgets.yml, config/locales/custom/nl/general.yml, config/locales/custom/nl/mailers.yml, config/locales/custom/nl/pages.yml, config/locales/custom/nl/settings.yml, config/locales/nl/budgets.yml, config/locales/nl/pages.yml, config/locales/nl/seeds.yml
=> Improve Dutch translations

app/components/budgets/investments_list_component.html.erb, app/components/budgets/investments_list_component.rb, spec/components/budgets/investments_list_component_spec.rb
Adjust show all investments button. Always show the button except on informing phase.
=> Adjust show all investments button

app/views/admin/newsletters/_form.html.erb, app/views/mailer/newsletter.html.erb, spec/system/admin/emails/newsletters_spec.rb
Allow send newsletters with images.
=> Allow send newsletters with images

app/assets/stylesheets/base.scss, app/views/shared/_header_content.html.erb
Fix margins on header content.
=> Fix margins on header content

app/views/admin/debates/show.html.erb, spec/system/admin/debates_spec.rb
Fix link to comments on admin view for debates
=> Fix link to comments on admin view for debates

app/assets/stylesheets/base.scss
Fix subnavigation dropdown menu styles.
=> Fix subnavigation dropdown menu styles

config/locales/custom/nl/general.yml
=> Update custom NL text

app/views/layouts/_mailer_footer.html.erb, config/locales/custom/nl/activerecord.yml, config/locales/en/mailers.yml, config/locales/es/mailers.yml, config/locales/nl/mailers.yml, spec/system/admin/system_emails_spec.rb
Add unsubscribe info on system emails.
=> Add unsubscribe info on system emails

app/assets/stylesheets/base.scss
Backport of https://github.com/StemvanGroningen/consul/pull/154.
Add background color to mobile menu.
=> Add background color to mobile menu

config/initializers/errbit.rb
Avoid Errbit sending notifications for not real errors.
=> Ignore more not real errors on Errbit

app/views/polls/_poll_header.html.erb
=> Fix poll summary alignment

config/schedule.rb
Avoid hard disk to get too full
=> Delete the content of log files every week

app/views/shared/_header.html.erb
Fix background image url on header.
=> Fix background image url on header

app/views/budgets/results/_results_table.html.erb
Remove duplicated content on budgets results.
=> Remove duplicated content on budgets results

app/assets/stylesheets/base.scss
Fix subnavigation dropdown z-index.
=> Fix subnavigation dropdown z-index

app/assets/stylesheets/base.scss, app/components/budgets/investments/ballot_component.html.erb, app/views/budgets/ballot/_progress_bar.html.erb, spec/system/budgets/investments_spec.rb
- Do not show price on budgets with hidden money.
- Add base styles.
- Remove duplicated content on progress bar.
=> Fixes after upgrade to 1.5.0

app/controllers/admin/stats_controller.rb
Show correct participants by district in the statistics
=> Show correct participants by district in the statistics

app/models/image.rb
Show large images with the correct size when after switching to ActiveStorage
=> Show large images with correct size using ActiveStorage

config/locales/custom/nl/admin.yml, config/locales/en/admin.yml, config/locales/es/admin.yml, lib/user_segments.rb, spec/lib/user_segments_spec.rb
Add investment followers user segment to Admin Newsletters.
=> Add investment followers user segment

app/helpers/site_customization_helper.rb, app/models/i18n_content.rb, config/locales/custom/nl/admin.yml, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/system/admin/site_customization/information_texts_spec.rb
Add budgets tab to admin site customization.
=> Add budgets tab to admin site customization

app/assets/stylesheets/base.scss
Fix investments list word break.
=> Fix investments list word break

app/helpers/polls_helper.rb, app/views/custom/polls/_poll_group.html.erb, app/views/polls/_poll_group.html.erb, spec/system/polls/polls_spec.rb
Change poll button if results are enabled using the same logic of the title with the `link_to_poll` method.
=> Change poll button if results are enabled

config/locales/custom/nl/devise.yml
=> Fix custom nl devise text

Gemfile.lock, Gemfile_custom, config/schedule.rb, lib/tasks/backup.rake
Create daily backups and store them in the cloud Mega.
Create the following keys on your `secrets.yml` to perform the backups:
```
mega_username: "your email account"
mega_password: "your password account"
```
=> Create daily backups and store them in the cloud Mega

app/assets/stylesheets/base.scss
Reduce budget header font size on small screens.
=> Reduce budget header font size on small screens

lib/admin_wysiwyg_sanitizer.rb, spec/lib/admin_wysiwyg_sanitizer_spec.rb
Add `br` tag to wysiwyg sanitizer.
=> Add br tag to wysiwyg sanitizer

app/assets/stylesheets/base.scss
Remove fix position on draft comments box.
=> Remove fix position on draft comments box

app/views/organizations/registrations/new.html.erb
Add margin top to organizations sign up button.
=> Add margin top to organizations sign up button

app/models/poll.rb, spec/system/polls/polls_spec.rb
Order expired polls by ends date.
=> Order expired polls by ends date

config/initializers/errbit.rb
Configure airbrake as Errbit documentation says
=> Configure airbrake as Errbit documentation says

app/models/widget/card.rb, app/views/budgets/results/show.html.erb, spec/system/budgets/results_spec.rb, spec/system/home_spec.rb
- Order homepage cards by created at.
- Replace back link on budgets results.
=> Homepage and budgets

app/models/concerns/attachable.rb
https://github.com/consuldemocracy/consuldemocracy/issues/5167
Avoid error when trying to update the name of an image
=> Avoid error when trying to update the name of an image

app/views/legislation/processes/_header.html.erb
Fix additional info button on legislation header. Show button only if additional info is present.
=> Fix additional info button on legislation header

spec/controllers/custom/budgets/investments_controller_spec.rb, spec/controllers/custom/debates_controller_spec.rb, spec/controllers/custom/legislation/annotations_controller_spec.rb, spec/controllers/custom/legislation/proposals_controller_spec.rb, spec/controllers/custom/legislation/questions_controller_spec.rb, spec/controllers/custom/polls_controller_spec.rb, spec/controllers/custom/proposals_controller_spec.rb
=> Add specs for comments order

app/assets/stylesheets/base.scss
Fixes after upgrade to version 2.0.1.
=> Fixes after upgrade

app/assets/stylesheets/base.scss
=> Fix subnavigation menu arrow

spec/system/custom/site_customization/custom_pages_spec.rb, spec/system/site_customization/custom_pages_spec.rb
Improve specs for the custom pages section. If the content that is not expected to find is in a different section of the website, the specs will fail. 😅
=> Improve custom pages specs

lib/tasks/backup.rake
Delete all the old backup folders if there are duplicates
=> Delete all the old backup folders if there are duplicates

app/assets/stylesheets/base.scss
Fix styles on comments box and social share button.
=> Fix styles on comments box and social share button

app/assets/stylesheets/base.scss
=> Fix draft panel styles

Gemfile.lock, Gemfile_custom
Lock version of gems to avoid future problems
=> Lock version of gems to avoid future problems

app/assets/stylesheets/base.scss
Remove fix position on comments box.
=> Remove fix position on comments box

app/assets/stylesheets/base.scss
=> Avoid horizontal overflow

app/views/custom/shared/_header.html.erb, app/views/shared/_header.html.erb, app/views/shared/_header_content.html.erb
Create custom shared header view.
=> Create custom shared header view

app/views/budgets/results/_results_table.html.erb
Remove duplicated column on budget results table.
=> Remove duplicated column on budget results table

app/assets/stylesheets/base.scss
=> Update word break CSS rule

app/assets/stylesheets/base.scss
=> Fix base styles
