config/sitemap.rb, spec/lib/tasks/sitemap_spec.rb
Don't include URLs in the sitemap that are not accessible because the process has been disabled, even if they exist, to avoid robots try to access those URLs and raise exceptions on the Rails server.
=> Don't include disabled processes in sitemap

config/initializers/active_record_logger.rb
By default, we see many lines this in the logs
```
DEBUG: Delayed::Backend::ActiveRecord::Job Load (1.1ms) ...
```
With this change, we avoid all debug logs for ActiveRecord
Other solutions and more info here https://github.com/collectiveidea/delayed_job/issues/886
=> Avoid delayed_job debug logs

app/views/pages/help/_processes.html.erb, config/locales/en/pages.yml, config/locales/es/pages.yml
Add missing information for processes in the help section. `/help`
=> Add processes feature info section in the help page

.travis.yml, Dockerfile, Gemfile, Gemfile.lock, README.md, README_ES.md, app/views/admin/homepage/_setting.html.erb, spec/features/admin/budget_phases_spec.rb, spec/features/admin/homepage/homepage_spec.rb, spec/features/admin/legislation/processes_spec.rb, spec/features/ckeditor_spec.rb, spec/rails_helper.rb, spec/shared/features/nested_documentable.rb, spec/support/common_actions/verifications.rb, spec/support/matchers/have_ckeditor.rb
Fix failures in specs using CKEditor
Commit list:
https://github.com/consul/consul/commit/5bf968d2b24fdafacce3ad2decea6a600f2afdb1
https://github.com/consul/consul/commit/59b625a5f90e615acb7e11b66d5d4b7aac0d464c
https://github.com/consul/consul/commit/2c4acb0bf78cd286c4e876970961a8fdc829290e
https://github.com/consul/consul/commit/72c2b87227d502c8a2875492a7480ada4e432884
https://github.com/consul/consul/commit/a0ea1f6ecb5404d6b706b68b070f4e61cdcea5f6
https://github.com/consul/consul/commit/2cdc6a1b1b11212ea5ea6268f628a24386529da4
https://github.com/consul/consul/commit/5b97b20f9605b90f5af48224d4b2677db3d01d49
https://github.com/consul/consul/commit/a103b5392ef291e52cda76313eb435e04eaf2bf3
https://github.com/consul/consul/commit/8408bfdcf00f7cb97b21b578e2caca4779cf1d6e …
=> Fix ckeditor specs failures

app/models/poll/question/answer.rb, spec/features/admin/poll/questions/answers/answers_spec.rb
Avoid the following error when trying to delete a poll with answers that contain videos.
```
PG::ForeignKeyViolation: ERROR: update or delete on table "poll_question_answers" violates 
foreign key constraint "fk_rails_52941e957e" on table "poll_question_answer_videos" 
DETAIL: Key (id)=(1) is still referenced from table "poll_question_answer_videos". : 
DELETE FROM "poll_question_answers" WHERE "poll_question_answers"."id" = $1
```
Added the option `dependent: :destroy` to the `has_many` relation
=> Allow deleting polls with answers including videos

spec/features/admin/legislation/processes_spec.rb
https://travis-ci.org/github/democrateam/consul/jobs/709127543
- Fix failing spec clicking Add Image button
When the screen size is small the web driver needs to do scroll down, but apparently, it does not get down enough and it cannot find the button to click it. Setting a window size big enough the button is clicked correctly.
=> Fix failing spec clicking Add Image button

app/models/legislation/answer.rb, spec/models/legislation/answer_spec.rb
When a legislation process is deleted, everything related will be deleted, including the answers. This `dependent: :destroy` was causing that admin users accounts were being accidentally deleted. Even when they were logged in they were logged out and not able to log in again.
=> Do not delete users when deleting legislation answers

config/initializers/wicked_pdf.rb
https://github.com/mileszs/wicked_pdf/issues/758
https://errors.democrateam.com/apps/5dff3119b2aa2903f8364ae0/problems/5eda06e1b2aa2902c6838a46
Avoid error when downloading a PDF poster for a proposal in production environments
=> Find correct path for WickedPdf on production

app/controllers/concerns/search.rb, spec/system/budgets/investments_spec.rb
Error https://errors.democrateam.com/apps/5dff36a7b2aa2903f8364ae4/problems/6113b955b2aa29034cf2a1e7
Avoid raising an error when combining advanced search with filtering for budget investments.
=> Avoid error when combining investments advanced search with filters

app/components/budgets/budget_component.html.erb
This is a backport of https://github.com/StemvanGroningen/consul/pull/135.
Use `original` image size instead of `large` on budget header.
=> Use original image size on budget header

app/assets/stylesheets/base.scss, app/controllers/concerns/admin/widget/cards_actions.rb, app/views/admin/widget/cards/_form.html.erb, app/views/shared/_header.html.erb, app/views/shared/_header_content.html.erb, config/locales/en/activerecord.yml, config/locales/es/activerecord.yml, db/migrate/20220203110757_add_background_image_to_widget_cards.rb, db/schema.rb, spec/system/custom/admin/cards_spec.rb
Add checkbox to use image as background on header cards.
=> Add checkbox to use image as background on header cards

app/views/users/registrations/new.html.erb, config/locales/en/devise_views.yml, config/locales/es/devise_views.yml, config/locales/nl/devise_views.yml
Add password note on user registrations new form.
=> Add password note on user registrations new

app/assets/stylesheets/base.scss, app/views/shared/_header.html.erb
Prevent homepage background image duplication.
When homepage header image is set as background is necessary to remove `header-card` class to avoid image duplication.
=> Prevent homepage background image duplication

app/assets/stylesheets/application.scss
Now in CONSUL there are two possible places to customize the styles, the `stylesheets/custom.scss` file and the `stylesheets/custom/` folder.
It seems that we accidentally deleted the `@import "custom"` which forced us to add all the files inside `stylesheets/custom/`. 😓  
This PR adds it back so we can continue to use the default `stylesheets/custom.scss` file. 😌
=> Import custom SCSS file

app/views/legislation/processes/_debate.html.erb, app/views/legislation/processes/debate.html.erb, config/locales/en/legislation.yml, config/locales/es/legislation.yml, spec/system/legislation/processes_spec.rb, spec/system/legislation/questions_spec.rb
Remove unnecessary alert on legislation processes.
=> Remove unnecessary alert on legislation processes

app/assets/stylesheets/base.scss
Improve subnavigation styles on mobile screens.
=> Improve subnavigation styles on mobile screens

app/assets/stylesheets/base.scss, app/models/legislation/draft_version.rb, lib/admin_legislation_sanitizer.rb, spec/models/legislation/draft_version_spec.rb
Add new tags on legislation markdown: `hr blockquote code table thead tbody th tr td`. Also fixes styles for admin markdown preview.
=> Add new tags on legislation markdown

app/assets/stylesheets/base.scss, app/views/budgets/ballot/_progress_bar.html.erb, app/views/budgets/investments/_header.html.erb, config/locales/custom/nl/budgets.yml, spec/system/budgets/investments_spec.rb
- Fix debate show votes alignment.
- Fix draft comments button alignment.
- Update custom NL texts.
- Show progress bar for all budgets: the condition `@budget.show_money?` is inside `budgets/ballot/progress_bar` partial. So, is no necessary in this view.
=> Fix layout styles

app/components/budgets/investments/votes_component.html.erb, spec/components/budgets/investments/votes_component_spec.rb
Show participation not allowed message on mobile. Now the message only appeared when hovering which is not possible on touch screen devices. This has been fixed in CONSUL version 1.5.
=> Show participation not allowed message on mobile

app/views/admin/poll/polls/_form.html.erb, app/views/polls/_poll_header.html.erb, app/views/polls/show.html.erb, config/locales/en/general.yml, config/locales/es/general.yml, config/locales/nl/general.yml, spec/system/admin/poll/polls_spec.rb, spec/system/admin/translatable_spec.rb, spec/system/polls/polls_spec.rb
Backport of https://github.com/StemvanGroningen/consul/pull/149.
- Add wysiwyg to poll description and summary.
- Add read less button on poll header.
- Fix data-toggle on poll answer description: the data-toggle ids should remain on the same line to work.
=> Poll header

app/models/legislation/annotation.rb, spec/system/legislation/draft_versions_spec.rb
Hide comment form on annotations when allegations phase is closed on legislation processes.
=> Hide comments when allegations phase is closed

app/assets/stylesheets/base.scss, app/views/polls/_gallery.html.erb, spec/system/polls/polls_spec.rb
Show orbit controls on image polls if there are more than one image.
=> Show orbit controls on image polls

app/assets/stylesheets/base.scss
Fix budget header for small images.
=> Fix budget header for small images

app/assets/stylesheets/base.scss
Fix small only breakpoint.
Prevent warning message when run some specs:
```
WARNING: breakpoint(): "small-only" is not defined in your `$breakpoints` or `$breakpoints-hidpi` setting.
on line 92:7 of ../../.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/foundation-rails-6.6.2.0/vendor/assets/scss/util/_breakpoint.scss, in function `breakpoint`
from line 152:11 of ../../.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/foundation-rails-6.6.2.0/vendor/assets/scss/util/_breakpoint.scss, in mixin `breakpoint`
from line 800:12 of app/assets/stylesheets/base.scss
from line 55:9 of app/assets/stylesheets/application.scss
```
=> Fix small only breakpoint

app/assets/stylesheets/base.scss, app/views/custom/legislation/processes/_process.html.erb, spec/system/budgets/budgets_spec.rb, spec/system/legislation/processes_spec.rb
- Fix poll message on mobile.
- Fix subnavigation menu on mobile.
- Hide phases list on mobile.
- Add links to legislation processes dates.
=> Design fixes for mobile devices

.github/workflows/tests.yml, app/views/account/show.html.erb, spec/system/account_spec.rb
Users can select the option "**Receive a summary of proposal notifications**" on the My Account `/account` page.
These notifications are created by proposal authors for users who have supported the proposal. 
To avoid confusion and improve the UX, this PR hides that checkbox if the proposals feature is disabled, as it doesn't make sense to show the option if those notifications cannot be created. 😌
=> Show email digest only if proposals are enabled

app/views/polls/index.html.erb
Replace format on polls description. This allows use text format and line breaks on polls description text.
=> Replace format on polls description

config/locales/nl/rails.yml
Add missing space on budgets dates.
=> Add missing space on budgets dates

app/assets/stylesheets/layout.scss, app/views/admin/legislation/processes/_form.html.erb, app/views/legislation/processes/_header.html.erb, app/views/legislation/processes/_header_full.html.erb, app/views/legislation/processes/_process.html.erb, config/locales/en/admin.yml, config/locales/es/admin.yml, spec/system/admin/legislation/processes_spec.rb
Replace legislation processes form markdown to CKEditor fields.
=> Replace legislation processes form markdown

app/assets/javascripts/application.js, app/assets/javascripts/authenticity_token_refresh.js
Avoid the following error when using Turbolinks
```
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
```
=> Refresh CSRF Token when using Turbolinks

app/components/admin/menu_component.rb
Add link to manage maps in the admin section. Maybe removed by error when upgrading to version 2.0.1
=> Add admin maps link

app/controllers/admin/budget_investments_controller.rb, app/views/admin/budget_investments/edit.html.erb, spec/shared/system/custom_admin_nested_documentable.rb, spec/shared/system/custom_admin_nested_imageable.rb, spec/system/custom/admin/budget_investments_spec.rb
Allow admins to include images or documents to investments.
=> Allow admins to include images or documents to investments

app/components/widget/feeds/process_component.html.erb
Prevents show HTML tags on widget feed after the changes of https://github.com/democrateam/consul/pull/132.
=> Sanitize process summary feed
